import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "./globals.css";
import ConvexClerkProvider from "@/components/providers/ConvexClerkProvider";
import Header from "@/components/Header";
import SyncUserWithConvex from "@/components/providers/SyncUserWithConvex";
import { Toaster } from "@/components/ui/toaster";

const manrope = Manrope({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ConvexClerkProvider>
      <html lang="en">
        <body className={`${manrope.className}  antialiased`}>
          <Toaster />
          <Header />
          <SyncUserWithConvex />
          {children}
        </body>
      </html>
    </ConvexClerkProvider>
  );
}
